// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST10174327_GiftOfTheGiversWebApp.Data;

#nullable disable

namespace ST10174327_GiftOfTheGiversWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251103095456_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.Disaster", b =>
                {
                    b.Property<int>("DISASTER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DISASTER_ID"));

                    b.Property<string>("AID_TYPE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisasterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ENDDATE")
                        .HasColumnType("date");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("LOCATION")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("STARTDATE")
                        .HasColumnType("date");

                    b.Property<string>("USERNAME")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DISASTER_ID");

                    b.ToTable("Disaster", (string)null);
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.GoodsAllocation", b =>
                {
                    b.Property<int>("GoodsAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsAllocationId"));

                    b.Property<string>("AidType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AllocationDate")
                        .HasColumnType("date");

                    b.Property<string>("CATEGORY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DISASTER_ID")
                        .HasColumnType("int");

                    b.Property<int?>("GOODSINVENTORY_ID")
                        .HasColumnType("int");

                    b.Property<int>("ITEM_COUNT")
                        .HasColumnType("int");

                    b.HasKey("GoodsAllocationId");

                    b.HasIndex("DISASTER_ID");

                    b.HasIndex("GOODSINVENTORY_ID");

                    b.ToTable("GoodsAllocation");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.GoodsDonation", b =>
                {
                    b.Property<int>("GOODS_DONATION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GOODS_DONATION_ID"));

                    b.Property<string>("CATEGORY")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DATE")
                        .HasColumnType("date");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DISASTER_ID")
                        .HasColumnType("int");

                    b.Property<string>("DONOR")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ITEM_COUNT")
                        .HasColumnType("int");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GOODS_DONATION_ID");

                    b.HasIndex("DISASTER_ID");

                    b.ToTable("GoodsDonation");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.GoodsInventory", b =>
                {
                    b.Property<int>("GOODS_INVENTORY_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GOODS_INVENTORY_ID"));

                    b.Property<string>("CATEGORY")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ITEM_COUNT")
                        .HasColumnType("int");

                    b.HasKey("GOODS_INVENTORY_ID");

                    b.ToTable("GoodsInventory");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.GoodsPurchase", b =>
                {
                    b.Property<int>("GoodsPurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsPurchaseID"));

                    b.Property<string>("CATEGORY")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GOODSINVENTORY_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("GoodsPurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GoodsTotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ITEM_COUNT")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GoodsPurchaseID");

                    b.HasIndex("GOODSINVENTORY_ID");

                    b.ToTable("GoodsPurchase");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.Money", b =>
                {
                    b.Property<int>("MoneyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoneyId"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RemainingMoney")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalMoney")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MoneyId");

                    b.ToTable("Money");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.MoneyAllocation", b =>
                {
                    b.Property<int>("MoneyAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoneyAllocationId"));

                    b.Property<string>("AidType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("AllocationAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AllocationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DISASTER_ID")
                        .HasColumnType("int");

                    b.HasKey("MoneyAllocationId");

                    b.HasIndex("DISASTER_ID");

                    b.ToTable("MoneyAllocation");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.MoneyDonation", b =>
                {
                    b.Property<int>("MONEY_DONATION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MONEY_DONATION_ID"));

                    b.Property<decimal>("AMOUNT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DATE")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int?>("DISASTER_ID")
                        .HasColumnType("int");

                    b.Property<string>("DONOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MONEY_DONATION_ID");

                    b.HasIndex("DISASTER_ID");

                    b.ToTable("MoneyDonation");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.TaskAssignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<string>("AdminFeedback")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HoursWorked")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<int>("VolunteerID")
                        .HasColumnType("int");

                    b.Property<string>("VolunteerNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AssignmentID");

                    b.HasIndex("TaskID");

                    b.HasIndex("VolunteerID");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.Volunteer", b =>
                {
                    b.Property<int>("VolunteerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteerID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Availability")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredAreas")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Skills")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VolunteerID");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.VolunteerTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrentVolunteers")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequiredVolunteers")
                        .HasColumnType("int");

                    b.Property<string>("SkillsRequired")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaskLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TaskID");

                    b.ToTable("VolunteerTasks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.GoodsAllocation", b =>
                {
                    b.HasOne("ST10174327_GiftOfTheGiversWebApp.Models.Disaster", "Disaster")
                        .WithMany("GoodsAllocations")
                        .HasForeignKey("DISASTER_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ST10174327_GiftOfTheGiversWebApp.Models.GoodsInventory", "GoodsInventory")
                        .WithMany("GoodsAllocations")
                        .HasForeignKey("GOODSINVENTORY_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Disaster");

                    b.Navigation("GoodsInventory");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.GoodsDonation", b =>
                {
                    b.HasOne("ST10174327_GiftOfTheGiversWebApp.Models.Disaster", "Disaster")
                        .WithMany("GoodsDonations")
                        .HasForeignKey("DISASTER_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Disaster");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.GoodsPurchase", b =>
                {
                    b.HasOne("ST10174327_GiftOfTheGiversWebApp.Models.GoodsInventory", "GoodsInventory")
                        .WithMany("GoodsPurchases")
                        .HasForeignKey("GOODSINVENTORY_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsInventory");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.MoneyAllocation", b =>
                {
                    b.HasOne("ST10174327_GiftOfTheGiversWebApp.Models.Disaster", "Disaster")
                        .WithMany("MoneyAllocations")
                        .HasForeignKey("DISASTER_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disaster");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.MoneyDonation", b =>
                {
                    b.HasOne("ST10174327_GiftOfTheGiversWebApp.Models.Disaster", "Disaster")
                        .WithMany("MoneyDonations")
                        .HasForeignKey("DISASTER_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Disaster");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.TaskAssignment", b =>
                {
                    b.HasOne("ST10174327_GiftOfTheGiversWebApp.Models.VolunteerTask", "VolunteerTask")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ST10174327_GiftOfTheGiversWebApp.Models.Volunteer", "Volunteer")
                        .WithMany("Tasks")
                        .HasForeignKey("VolunteerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Volunteer");

                    b.Navigation("VolunteerTask");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.Disaster", b =>
                {
                    b.Navigation("GoodsAllocations");

                    b.Navigation("GoodsDonations");

                    b.Navigation("MoneyAllocations");

                    b.Navigation("MoneyDonations");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.GoodsInventory", b =>
                {
                    b.Navigation("GoodsAllocations");

                    b.Navigation("GoodsPurchases");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.Volunteer", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ST10174327_GiftOfTheGiversWebApp.Models.VolunteerTask", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
